// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_get from "./routes/api/get.ts";
import * as $api_submit from "./routes/api/submit.ts";
import * as $index from "./routes/index.tsx";
import * as $Get from "./islands/Get.tsx";
import * as $Submit from "./islands/Submit.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/get.ts": $api_get,
    "./routes/api/submit.ts": $api_submit,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Get.tsx": $Get,
    "./islands/Submit.tsx": $Submit,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
